services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-vue3
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - db
    command: php artisan serve --host=0.0.0.0 --port=8000
    environment:
      - DB_HOST=db

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - db_data:/var/lib/mysql

  vite:
    build:
      context: .
      dockerfile: Dockerfile.vite
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --host

volumes:
  db_data:
